function convertMATLABCodeToStylish(inputFile, outputFile)
    % Read original HTML
    html = fileread(inputFile);

    % 1) Remove MATLAB's default .S0–.S5 style block
    html = regexprep(html, ...
        '<style[^>]*>.*?\.S0[^<]*?.*?</style>', ...
        '', 'once', 'dotexceptnewline');

    % 2) Inject external CSS link into <head>
    cssLink = ['<link rel="stylesheet" href="../assets/styles.css">' newline];
    html = regexprep(html, '(<head[^>]*>)', ['$1' cssLink], 'once');

    % 3) Wrap <body> in a centered container
    html = regexprep(html, '(<body[^>]*>)', ['$1' newline '<div class="container">'], 'once');
    html = strrep(html, '</body>', ['</div>' newline '</body>']);

    % 4) Remove MATLAB‐generated title + subtitle in‐body
    html = regexprep(html, '(?s)<h1[^>]*class\s*=\s*''S0''.*?</h1>.*?<div[^>]*class\s*=\s*''S1''.*?</div>\s*', '', 'once');

    % 5) Inject our own header (single source of truth)
    tk = regexp(html, '<title>(.*?)</title>', 'tokens', 'once');
    pageTitle = ''; if ~isempty(tk), pageTitle = tk{1}; end
    pageDate  = datestr(now, 'dd-mmm-yyyy');
    headerHTML = sprintf([ ...
        '<header class="page-header">\n' ...
        '  <h1>%s</h1>\n' ...
        '  <p class="meta">Date: %s</p>\n' ...
        '</header>\n'], pageTitle, pageDate);
    html = regexprep(html, '(<div class="container">)', ['$1' newline headerHTML], 'once');

    % 6) Build combined footer + copy‐button script
    footerHTML = [ ...
      '<footer class="page-footer">' newline ...
      '  <p>Powered by <a href="https://github.com/yourrepo/euler">Euler</a></p>' newline ...
      '</footer>' newline ...
    ];
    copyJs = [ ...
      '<script>' newline ...
      'document.querySelectorAll(".inlineWrapper").forEach(function(wrapper){' newline ...
      '  var text = wrapper.innerText.trim();' newline ...
      '  if(!text) return;' newline ...
      '  var btn = document.createElement("button"); btn.textContent="Copy";' newline ...
      '  btn.onclick = function(){ navigator.clipboard.writeText(text); btn.textContent="Copied!"; setTimeout(function(){btn.textContent="Copy";},2000); };' newline ...
      '  Object.assign(btn.style,{position:"absolute",top:"6px",right:"8px",backgroundColor:"#444",color:"#eee",border:"none",padding:"2px 6px",fontSize:"11px",borderRadius:"3px",cursor:"pointer",opacity:"0.8"});' newline ...
      '  wrapper.style.position="relative"; wrapper.appendChild(btn);' newline ...
      '});' newline ...
      '</script>' newline ...
    ];

    % 7) Single‐regex to inject footer + copy‐JS before </body>
    html = regexprep(html, ...
        '(</body>)', ...
        [footerHTML copyJs '$1'], ...
        'once', 'dotall');

    % 8) Write out the final HTML
    fid = fopen(outputFile, 'w');
    fwrite(fid, html);
    fclose(fid);
end